kind: Service
apiVersion: v1
metadata:
  name: csi-sidecar-nfs-provisioner
  labels:
    app: csi-sidecar-nfs-provisioner
spec:
  selector:
    app: csi-sidecar-nfs-provisioner
  ports:
    - name: dummy
      port: 12345

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: csi-sidecar-nfs-provisioner
spec:
  replicas: 2
  selector:
    matchLabels:
      external-attacher: csi-sidecar-nfs-provisioner
  template:
    metadata:
      labels:
        external-attacher: csi-sidecar-nfs-provisioner
    spec:
      serviceAccount: csi-provisioner
      containers:
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v1.1.0
          args:
            - "--provisioner=com.nfs.csi.xsky"
            - "--csi-address=$(ADDRESS)"
            - "--v=5"
            - "--timeout=60s"
            - "--retry-interval-max=2m"
          env:
            - name: ADDRESS
              value: /var/lib/kubelet/plugins_registry/csi-xsky-nfs-driver/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/kubelet/plugins_registry/csi-xsky-nfs-driver
            - name: timezone
              mountPath: /etc/localtime
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/csi-xsky-nfs-driver
            type: DirectoryOrCreate
        - name: timezone
          hostPath:
            path: /etc/localtime