kind: Service
apiVersion: v1
metadata:
  name: csi-xsky-iscsiplugin-provisioner
  labels:
    app: csi-xsky-iscsiplugin-provisioner
spec:
  selector:
    app: csi-xsky-iscsiplugin-provisioner
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: csi-xsky-iscsiplugin-provisioner
spec:
  serviceName: "csi-xsky-iscsiplugin-provisioner"
  replicas: 2
  template:
    metadata:
      labels:
        app: csi-xsky-iscsiplugin-provisioner
    spec:
      serviceAccount: csi-provisioner
      containers:
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v1.0.0
          args:
            - "--provisioner=csi-xsky-iscsiplugin"
            - "--csi-address=$(ADDRESS)"
            - "--v=5"
            - "--enable-leader-election=true"
          env:
            - name: ADDRESS
              value: /var/lib/kubelet/plugins_registry/csi-xsky-iscsiplugin/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/kubelet/plugins_registry/csi-xsky-iscsiplugin
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/csi-xsky-iscsiplugin
            type: DirectoryOrCreate
