kind: Service
apiVersion: v1
metadata:
  name: csi-xsky-iscsiplugin-attacher
  labels:
    app: csi-xsky-iscsiplugin-attacher
spec:
  selector:
    app: csi-xsky-iscsiplugin-attacher
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: csi-xsky-iscsiplugin-attacher
spec:
  serviceName: "csi-xsky-iscsiplugin-attacher"
  replicas: 2
  template:
    metadata:
      labels:
        app: csi-xsky-iscsiplugin-attacher
    spec:
      serviceAccount: csi-attacher
      containers:
        - name: csi-xsky-iscsiplugin-attacher
          image: quay.io/k8scsi/csi-attacher:v1.0.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--leader-election"
            - "--leader-election-namespace=$(MY_NAMESPACE)"
            - "--leader-election-identity=$(MY_NAME)"
            env:
              - name: MY_NAME
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.name
              - name: MY_NAMESPACE
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
              - name: ADDRESS
                value: /var/lib/kubelet/plugins_registry/csi-xsky-iscsiplugin/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/kubelet/plugins_registry/csi-xsky-iscsiplugin
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/csi-xsky-iscsiplugin
            type: DirectoryOrCreate
